//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WT_Lab_Pracs {
	
	
	public partial class FP {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
	}
}
