//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WT_Lab_Pracs {
	
	
	public partial class register {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox name;
		
		protected System.Web.UI.WebControls.TextBox password;
		
		protected System.Web.UI.WebControls.TextBox password2;
		
		protected System.Web.UI.WebControls.TextBox email;
		
		protected System.Web.UI.WebControls.TextBox contact_number;
	}
}
